import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import AppSidebar from "@/components/AppSidebar";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { SidebarProvider } from "@/components/ui/sidebar";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Fetch the cookies to determine the default theme
  const cookiesStore = await cookies();
  const defaultTheme = cookiesStore.get("sidebar_state")?.value === "system";
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(
        "min-h-screen font-sans antialiased",
        geistSans.variable, geistMono.variable, inter.variable
      )}>
        {/* All configuration properties must sit cleanly within the tag brackets */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
      
            <SidebarProvider defaultOpen={defaultTheme}>
              <AppSidebar />
              <main className="flex-1 flex flex-col">
                <Navbar />
                <div className="p-6 flex-1">
                  {children}
                </div>
              </main>
            </SidebarProvider>
          
        </ThemeProvider>
      </body>
    </html>
  );
}
